DROP TABLE IF EXISTS `session`;

CREATE TABLE session (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(255) DEFAULT NULL,
  `user_first_name` VARCHAR(255) DEFAULT NULL,
  `user_last_name` VARCHAR(255) DEFAULT NULL,
  `screen_width` INT(11) DEFAULT NULL,
  `screen_height` INT(11) DEFAULT NULL,
  `visits` INT(11) DEFAULT NULL,
  `page_response` TEXT DEFAULT NULL,
  `domain` VARCHAR(255) DEFAULT NULL,
  `path` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO session (
  `user_email`,
  `user_first_name`,
  `user_last_name`,
  `screen_width`,
  `screen_height`,
  `visits`,
  `page_response`,
  `domain`,
  `path`
) VALUES
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('test@email.com', 'test', 'user', 300, 500, 3, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/benefits'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('new@email.com', 'new', 'user', 800, 2000, 20, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/customers#finance'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company'),
  ('last@email.com', 'last', 'user', 1000, 200, 10, '<html><head></head><body><h1>test</h1></body</html>','https://www.quantummetric.com/', '/company');
