version: '3'
services:
  app:
    image: node
    working_dir: /srv/app
    volumes:
      - ./:/srv/app
    ports:
      - "3000:3000"
    command: "npm start"
    environment:
      DATABASE: quantum
      USER: quantum
      PASSWORD: quantum

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quantum
      MYSQL_USER: quantum
      MYSQL_PASSWORD: quantum
    volumes:
      - ./db:/var/lib/mysql
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
